name: Go

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build manpages
        run : |
          sudo apt install pandoc
          pandoc doc/instructor.1.md -s -t man | gzip | tee doc/instructor.1.gz > doc/ins.1.gz
      - name: Set version
        run : git tag "$(cat version)" || echo "Tag already exists"
      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v2.1.1
        with:
          args: release --skip-publish --rm-dist
      - name: Remove obsolete files in dist dir
        run : cd dist && rm -rf $(ls | find . -maxdepth 1 -type d -printf '%f\n') || rm config.yaml
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: dist/*
